# Generated by Django 4.2.2 on 2023-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_certificate_filepath_filmwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="type",
            field=models.TextField(
                choices=[("movie", "movie"), ("tv-show", "tv-show")],
                default="movie",
                verbose_name="type",
            ),
        ),
    ]
