# Generated by Django 4.2.2 on 2023-06-22 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_field_name_as_sqlite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
